modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
${mod_description}
'''
authors="${mod_authors}"

[[dependencies.${mod_id}]]
    modId="infinitymaxapi"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.10.0,4.11.0)"
    ordering="NONE"
    side="BOTH"